version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk-node-browsers-legacy
    steps:
      - checkout
  test:
    docker:
      - image: circleci/openjdk:11-jdk-node-browsers-legacy
    steps:
      - checkout
  jibBuildTar:
    docker:
      - image: circleci/openjdk:11-jdk-node-browsers-legacy
    steps:
      - checkout

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
      - jibBuildTar
