version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk-node-browsers-legacy
    steps:
      - checkout
      - run: sh gradlew build
  approve:
    steps: |
      curl -X POST -H 'Content-type: application/json' \
        --data "{\"text\": \"Please approve workflow from <https://circleci.com/workflow-run/${CIRCLE_WORKFLOW_ID}|here>.\"}" \
        $SLACK_WEBHOOK_URL
  jibBuildTar:
    docker:
      - image: circleci/openjdk:11-jdk-node-browsers-legacy
    steps:
      - checkout
      - run: sh gradlew jibBuildTar

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - approve:
          requires:
            - build
      - jibBuildTar:
          requires:
            - approve

