version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk-node-browsers-legacy
    steps:
      - checkout
#      - run:'sh gradlew build'
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
